version: 2.1
orbs:
  node: circleci/node@4.0.0

jobs:
  deploy_function:
    parameters:
      function_dir:
        type: string
      trigger_type:
        type: string
      trigger_event:
        type: string
      trigger_resource:
        type: string
      entry_point:
        type: string
    docker:
      - image: google/cloud-sdk:latest
    steps:
      - checkout
      - run:
          name: "Authenticate GCP"
          command: |
            echo $GOOGLE_AUTH > ${HOME}/gcp-key.json
            gcloud auth activate-service-account --key-file=${HOME}/gcp-key.json
      - run:
          name: "Deploy Function"
          command: |
            if [ "<< parameters.trigger_type >>" = "http" ]; then
              gcloud functions deploy << parameters.function_dir >> --runtime nodejs16 --trigger-http --entry-point=<< parameters.entry_point >> --source=./functions/<< parameters.function_dir >> --region=us-east1 --project=new-project-422101 --allow-unauthenticated
            else
              gcloud functions deploy << parameters.function_dir >> --runtime nodejs16 --trigger-event << parameters.trigger_event >> --trigger-resource << parameters.trigger_resource >> --entry-point=<< parameters.entry_point >> --source=./functions/<< parameters.function_dir >> --region=us-east1 --project=new-project-422101 --allow-unauthenticated

workflows:
  version: 2
  build_test_all_functions:
    jobs:
      - deploy_function:
          matrix:
            alias: deploy_specific_functions
            parameters:
              - function_dir: "helloHttp"
                trigger_type: "http"
                trigger_event: ""
                trigger_resource: ""
                entry_point: "helloHttp"
              - function_dir: "helloGCS"
                trigger_type: "event"
                trigger_event: "google.storage.object.finalize"
                trigger_resource: "harness235"
                entry_point: "helloGCS"
