version: 2.1

jobs:
  deploy_function:
    parameters:
      config:
        type: string
    docker:
      - image: google/cloud-sdk:latest
    steps:
      - checkout
      - run:
          name: "Authenticate GCP"
          command: |
            echo $GOOGLE_AUTH > ${HOME}/gcp-key.json
            gcloud auth activate-service-account --key-file=${HOME}/gcp-key.json
      - run:
          name: "Deploy Function"
          command: |
            if [ "<< parameters.trigger_type >>" = "http" ]; then
              gcloud functions deploy << parameters.function_dir >> --runtime nodejs16 --trigger-http --entry-point=<< parameters.entry_point >> --source=/workspace/<< parameters.function_dir >> --region=us-east1 --project=new-project-422101 --allow-unauthenticated
            else
              gcloud functions deploy << parameters.function_dir >> --runtime nodejs16 --trigger-event << parameters.trigger_event >> --trigger-resource << parameters.trigger_resource >> --entry-point=<< parameters.entry_point >> --source=/workspace/<< parameters.function_dir >> --region=us-east1 --project=new-project-422101 --allow-unauthenticated

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - deploy_function:
          matrix:
            parameters:
              config: [
                '{"function_dir": "helloHttp", "trigger_type": "http", "trigger_event": "", "trigger_resource": "", "entry_point": "helloHttp"}',
                '{"function_dir": "helloGCS", "trigger_type": "event", "trigger_event": "google.storage.object.finalize", "trigger_resource": "harness235", "entry_point": "helloGCS"}'
              ]
