version: 2.1
orbs:
  node: circleci/node@4.0.0
jobs:
  build_and_test:
    parameters:
      function_dir:
        type: string
    docker:
      - image: cimg/node:22.0.0
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
          app-dir: << parameters.function_dir >>
      - persist_to_workspace:
          root: .
          paths:
            - << parameters.function_dir >>
  deploy_function:
    parameters:
      function_dir:
        type: string
    docker:
      - image: google/cloud-sdk:latest
    steps:
      - checkout
      - run:
          name: "Authenticate GCP"
          command: |
            echo $GOOGLE_AUTH | jq '.' > ${HOME}/gcp-key.json
            cat ${HOME}/gcp-key.json
            gcloud auth activate-service-account --key-file=${HOME}/gcp-key.json
      - run:
          name: "Deploy Function"
          command: |
            gcloud functions deploy << parameters.function_dir >> --runtime nodejs14 --trigger-http --entry-point=myEntryPoint --region=us-central1 --allow-unauthenticated
workflows:
  version: 2
  build_test_all_functions:
    jobs:
      - build_and_test:
          matrix:
            parameters:
              function_dir: ["function-gcs", "function-http"] # List all directories
      - deploy_function:
          matrix:
            parameters:
              function_dir: ["function-gcs", "function-http"] # List all directories
