version: 2.1

jobs:
  deploy_function:
    parameters:
      project_id:
        type: string
      function_config:
        type: string
    docker:
      - image: google/cloud-sdk:latest
    steps:
      - checkout
      - run:
          name: "Authenticate GCP"
          command: |
            echo $GOOGLE_AUTH > ${HOME}/gcp-key.json
            gcloud auth activate-service-account --key-file=${HOME}/gcp-key.json
      - run:
          name: "Deploy Function"
          command: python3 ./deploy_functions.py '<< parameters.function_config >>'

workflows:
  version: 2
  dev_deployment:
    jobs:
      - deploy_function:
          name: "Deploy to Project1"
          context: dev-context  # Contexts are used to securely pass environment-specific variables
          matrix:
            parameters:
              project_id: ["project1"]
              function_config: ['{"function_dir": "helloHttp", "trigger_type": "http", "trigger_event": "", "trigger_resource": "", "entry_point": "helloHttp"}']
          filters:
            branches:
              only: dev

  main_deployment:
    jobs:
      - deploy_function:
          name: "Deploy to QA"
          context: qa-context
          matrix:
            parameters:
              project_id: ["new-project"]
              function_config: ['{"function_dir": "helloHttp", "trigger_type": "http", "trigger_event": "", "trigger_resource": "", "entry_point": "helloHttp"}']
          filters:
            branches:
              only: main
      - hold:
          type: approval
          name: "Hold for Preprod"
          filters:
            branches:
              only: main
      - deploy_function:
          name: "Deploy to Preprod"
          context: preprod-context
          matrix:
            parameters:
              project_id: ["preprod-project"]
              function_config: ['{"function_dir": "helloHttp", "trigger_type": "http", "trigger_event": "", "trigger_resource": "", "entry_point": "helloHttp"}']
          requires:
            - "Hold for Preprod"
          filters:
            branches:
              only: main
      - hold:
          type: approval
          name: "Hold for Prod"
          filters:
            branches:
              only: main
      - deploy_function:
          name: "Deploy to Prod"
          context: prod-context
          matrix:
            parameters:
              project_id: ["prod-project"]
              function_config: ['{"function_dir": "helloHttp", "trigger_type": "http", "trigger_event": "", "trigger_resource": "", "entry_point": "helloHttp"}']
          requires:
            - "Hold for Prod"
          filters:
            branches:
              only: main

