version: 2.1

jobs:
  deploy_function:
    parameters:
      config:
        type: string
    docker:
      - image: google/cloud-sdk:latest
    steps:
      - checkout
      - run:
          name: "Authenticate GCP"
          command: |
            echo $GOOGLE_AUTH > ${HOME}/gcp-key.json
            gcloud auth activate-service-account --key-file=${HOME}/gcp-key.json
      - run:
          name: "Deploy Function"
          command: python3 ./deploy_function.py '<< parameters.config >>'

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - deploy_function:
          matrix:
            parameters:
              config: [
                '{"function_dir": "helloHttp", "trigger_type": "http", "trigger_event": "", "trigger_resource": "", "entry_point": "helloHttp"}',
                '{"function_dir": "helloGCS", "trigger_type": "event", "trigger_event": "google.storage.object.finalize", "trigger_resource": "harness235", "entry_point": "helloGCS"}'
              ]
