version: 2.1
orbs:
  node: circleci/node@4.0.0
jobs:
  build_and_test:
    parameters:
      function_dir:
        type: string
    docker:
      - image: cimg/node:22.0.0
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
          app-dir: << parameters.function_dir >>
      - persist_to_workspace:
          root: .
          paths:
            - << parameters.function_dir >>
  deploy_function:
    parameters:
      function_dir:
        type: string
      trigger_type:
        type: string
      trigger_event:
        type: string
        default: ""
      trigger_resource:
        type: string
        default: ""
    docker:
      - image: google/cloud-sdk:latest
    steps:
      - checkout
      - run:
          name: "Authenticate GCP"
          command: |
            echo $GOOGLE_AUTH > ${HOME}/gcp-key.json
            gcloud auth activate-service-account --key-file=${HOME}/gcp-key.json
      - run:
          name: "Deploy Function"
          command: |
            if [ "<< parameters.trigger_type >>" = "http" ]; then
              gcloud functions deploy << parameters.function_dir >> \
                --runtime nodejs16 \
                --trigger-http \
                --entry-point=<< parameters.function_dir >> \
                --source=./<< parameters.function_dir >> \
                --region=us-east1 \
                --project=new-project-422101 \
                --allow-unauthenticated
            else
              gcloud functions deploy << parameters.function_dir >> \
                --runtime nodejs16 \
                --trigger-event << parameters.trigger_event >> \
                --trigger-resource << parameters.trigger_resource >> \
                --entry-point=<< parameters.function_dir >> \
                --source=./<< parameters.function_dir >> \
                --region=us-east1 \
                --project=new-project-422101 \
                --allow-unauthenticated
            fi
workflows:
  version: 2
  build_test_all_functions:
    jobs:
      - build_and_test:
          matrix:
            parameters:
              function_dir: ["helloGCS", "helloHttp"] # List all directories
      - deploy_function:
          matrix:
            parameters:
              function_dir: ["helloHttp", "helloGCS"] # List all directories
              trigger_type: ["http", "event"]
              trigger_event: ["", "google.storage.object.finalize"]
              trigger_resource: ["", "harness235"]
