version: 2.1

jobs:
  deploy_function:
    parameters:
      function_config:
        type: string
    docker:
      - image: google/cloud-sdk:latest
    steps:
      - checkout
      - run:
          name: "Authenticate GCP"
          command: |
            echo $GOOGLE_AUTH > ${HOME}/gcp-key.json
            gcloud auth activate-service-account --key-file=${HOME}/gcp-key.json
      - run:
          name: "Deploy Function"
          command: python3 ./deploy_functions.py '<< parameters.function_config >>'

workflows:
  version: 2
  dev_deployment:
    jobs:
      - deploy_function:
          name: "Deploy to Dev"
          context: dev-context
          matrix:
            parameters:
              function_config: [
                '{"project_id": "project1", "function_dir": "helloHttp", "trigger_type": "http", "trigger_event": "", "trigger_resource": "", "entry_point": "helloHttp"}',
                '{"project_id": "project1", "function_dir": "helloGCS", "trigger_type": "event", "trigger_event": "google.storage.object.finalize", "trigger_resource": "harness235", "entry_point": "helloGCS"}'
              ]
          filters:
            branches:
              only: dev

  main_deployment:
    jobs:
      - deploy_function:
          name: "Deploy to QA"
          context: qa-context
          matrix:
            parameters:
              function_config: [
                '{"project_id": "project2", "function_dir": "helloHttp", "trigger_type": "http", "trigger_event": "", "trigger_resource": "", "entry_point": "helloHttp"}',
                '{"project_id": "project2", "function_dir": "helloGCS", "trigger_type": "event", "trigger_event": "google.storage.object.finalize", "trigger_resource": "harness235", "entry_point": "helloGCS"}'
              ]
          filters:
            branches:
              only: main
      - hold:
          type: approval
          name: "Hold for Preprod"
          filters:
            branches:
              only: main
      - deploy_function:
          name: "Deploy to Preprod"
          context: preprod-context
          matrix:
            parameters:
              function_config: [
                '{"project_id": "project3", "function_dir": "helloHttp", "trigger_type": "http", "trigger_event": "", "trigger_resource": "", "entry_point": "helloHttp"}',
                '{"project_id": "project3", "function_dir": "helloGCS", "trigger_type": "event", "trigger_event": "google.storage.object.finalize", "trigger_resource": "harness235", "entry_point": "helloGCS"}'
              ]
          requires:
            - "Hold for Preprod"
          filters:
            branches:
              only: main
      - hold:
          type: approval
          name: "Hold for Prod"
          filters:
            branches:
              only: main
      - deploy_function:
          name: "Deploy to Prod"
          context: prod-context
          matrix:
            parameters:
              function_config: [
               '{"project_id": "project4", "function_dir": "helloHttp", "trigger_type": "http", "trigger_event": "", "trigger_resource": "", "entry_point": "helloHttp"}',
               '{"project_id": "project4", "function_dir": "helloGCS", "trigger_type": "event", "trigger_event": "google.storage.object.finalize", "trigger_resource": "harness235", "entry_point": "helloGCS"}'
              ]
          requires:
            - "Hold for Prod"
          filters:
            branches:
              only: main
